version: "2.1"
services:
  minthcm-web:
    image: minthcm/minthcm
    restart: always
    ports:
      - "172.17.0.1:50159:80"
    expose:
      - "80"
    hostname: minthcm-www
    depends_on:
      - minthcm-db
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    volumes:
      - ./storage/minthcm_www:/var/www/html
      - ./storage/minthcm_cron:/var/spool/cron/crontabs

  minthcm-db:
    image: percona:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      SYS_NICE: CAP_SYS_NICE
    volumes:
      - ./storage/minthcm_db:/var/lib/mysql

  minthcm-es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.3"
    volumes:
      - ./storage/minthcm_es:/usr/share/elasticsearch/data
    mem_limit: 4g
    environment:
      - node.name=es1
      - cluster.name=minthcm
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
